---
- hosts: webservers
  become: true
  tasks:

    - name: Check if apache2 service is running on AWS Server, else start it.
      service: name=apache2 state=started
      notify: restart apache2

    - name: Copy local index.html file to AWS Server /var/www/html directory.
      copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: 0555
        
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
...
