---
- hosts: webservers
  become: true
  tasks:

    - name: Install/Update apache2 on AWS Server
      apt:
        name: apache2
        update_cache: yes
        state: latest
        cache_valid_time: 86400

    - name: Start apache2 on AWS Server
      service:
        name: apache2
        state: started
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
...
