---
- hosts: webservers
  become: true
  tasks:

    - name: Stop apache2 service on AWS Server if its running
      service: name=apache2 state=stopped
      notify: stop apache2

    - name: Uninstall apache2 on AWS Server
      apt:
        pkg: apache2
        state: absent
      notify: uninstall apache2

  handlers:
    - name: stop apache2
      service: name=apache2 state=stopped

    - name: uninstall apache2
      apt:
        pkg: apache2
        state: absent
        purge: yes
        force: yes
...
